"""make user_id is unique for model UserRoles

Revision ID: a3cd3accd3cf
Revises: a2ec22eeb6ae
Create Date: 2026-07-21 21:10:17.587772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3cd3accd3cf'
down_revision: Union[str, Sequence[str], None] = 'a2ec22eeb6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_roles_user_id_key'), 'user_roles', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_roles_user_id_key'), 'user_roles', type_='unique')
    # ### end Alembic commands ###
